$ANSIBLE_VAULT;1.1;AES256
36393864656337633236386238366531616433366335383636626564386139306331636238653662
3165383130643062303733363239376334353763323535650a616430373637633765303861386339
38633862343032663138306164323737356532363834386561343837626130636438316335643737
6535383763393761330a643731333135376233373665633037363561613334303163346237666335
31383233313964346339346432656361333964313363363565633335633464303732663463666434
3865383934393333623661663732343065613333313266643032
